- hosts: k8s
  connection: local
  tasks:
    - name: Deploy stable app
      command: kubectl apply -f kubernetes/stable-deployment.yaml

    - name: Deploy service
      command: kubectl apply -f kubernetes/service.yaml

    - name: Deploy canary app
      command: kubectl apply -f kubernetes/canary-deployment.yaml
